# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest tqdm pytest-cov
        pip install -r requirements.txt

    - name: Lint with ruff
      run: |
        # stop the build if there are Python syntax errors or undefined names
        ruff check

    - name: Spin up Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install libosmesa6 libglx-mesa0 libopengl0 libglx0 libdbus-1-3 xvfb libx11-xcb-dev libxcb-cursor0
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;

    - name: Test with pytest
      run: |
        pip install -e .
        pytest --cov-report term-missing --cov mne_rsa
